### ISSUE TITLE
Convert.py Error

### ISSUE THREAD

**Issue by kva1980** [N4SOC/fortilogcsv#6]
I get below error during the conversion of log using the script convert.py

Traceback (most recent call last):
  File "C:\Temp\FW Logs\convert.py", line 20, in <module>
    for line in log_data:
  File "C:\Users\akamburvenk2\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 191: character maps to <undefined>

**Comment by generalsnipe** [comment]
What version firmware are you on?

**Comment by kva1980** [comment]
Its 5.6.3

**Comment by mrrothe** [comment]
Just committed a change to read files in UTF-8 which should resolve this
